### ISSUE TITLE
[PE Builder] Qual/quant need better empty display handling

### ISSUE THREAD

**Issue by DylanBell** [sixthedge/opentbl#95]
Should have message for empty quant, better message for empty qual, maybe cool images some day

**Comment by jcamou** [comment]
@DylanBell - Not sure if this falls under this but when there's no results to view the breadcrumbs, main header, and subnav all disappear

<img width="1277" alt="screenshot 2017-06-07 17 17 17" src="https://user-images.githubusercontent.com/411797/26902046-d5616c50-4ba5-11e7-80d1-03e800ff7a9e.png">

Can we make it so that the check for empty is done within the results so we get something more like this where the red rectangle is the message

<img width="1213" alt="screenshot 2017-06-07 17 23 18" src="https://user-images.githubusercontent.com/411797/26902133-1a16af18-4ba6-11e7-8dad-d49c3f032d80.png">

**Comment by DylanBell** [comment]
I was looking at empty messages within the builder itself, but ill wrap that issue into this one

**Comment by jcamou** [comment]
Ah didn't realize it was the builder I thought this was for the results. My bad

**Comment by DylanBell** [comment]
Not a problem
